import type { ShelfWork } from "./shelf";

/**
 * Country of origin for shelf works — literary source, not translation language
 * and not the Map's city hubs (London / Paris / New York).
 *
 * Resolution: per-work override → author → language default.
 */
const LANG_COUNTRY: Record<string, string> = {
  Arabic: "Egypt",
  Bengali: "India",
  Catalan: "Spain",
  Chinese: "China",
  Czech: "Czechia",
  Danish: "Denmark",
  Dutch: "Netherlands",
  Finnish: "Finland",
  French: "France",
  German: "Germany",
  Greek: "Greece",
  Hebrew: "Palestine",
  Hindi: "India",
  Hungarian: "Hungary",
  Icelandic: "Iceland",
  Italian: "Italy",
  Japanese: "Japan",
  Korean: "Korea",
  Latin: "Italy",
  Norwegian: "Norway",
  "Old Norse": "Iceland",
  Persian: "Iran",
  Polish: "Poland",
  Portuguese: "Portugal",
  Romanian: "Romania",
  Russian: "Russia",
  Spanish: "Spain",
  Swedish: "Sweden",
  Tamil: "India",
  Turkish: "Turkey",
  Ukrainian: "Ukraine",
  Yiddish: "Poland",
  // English has no safe default — see AUTHOR_COUNTRY / WORK_COUNTRY.
};

const AUTHORS_BY_COUNTRY: Record<string, readonly string[]> = {
  "United States": [
    "Abraham Cahan",
    "Ambrose Bierce",
    "Amy Lowell",
    "Anzia Yezierska",
    "Bret Harte",
    "Carl Sandburg",
    "Charles W. Chesnutt",
    "Charlotte Perkins Gilman",
    "Conrad Aiken",
    "Countee Cullen",
    "Dashiell Hammett",
    "Djuna Barnes",
    "Edgar Allan Poe",
    "Edgar Lee Masters",
    "Edith Wharton",
    "Edna St. Vincent Millay",
    "Edward Bellamy",
    "Edwin Arlington Robinson",
    "Elinor Wylie",
    "Ella Wheeler Wilcox",
    "Emily Dickinson",
    "Emma Lazarus",
    "Ernest Hemingway",
    "Evelyn Scott",
    "Ezra Pound",
    "Ezra Pound (after Li Bai et al.)",
    "F. Scott Fitzgerald",
    "Frances E. W. Harper",
    "Frank Norris",
    "George Washington Cable",
    "Gertrude Stein",
    "H. D. (Hilda Doolittle)",
    "Hamlin Garland",
    "Harold Frederic",
    "Hart Crane",
    "Helen Hunt Jackson",
    "Henry James",
    "Henry Wadsworth Longfellow",
    "Herman Melville",
    "Jack London",
    "James Branch Cabell",
    "James Weldon Johnson",
    "Jean Toomer",
    "Jessie Redmon Fauset",
    "John Dos Passos",
    "John Gould Fletcher",
    "Joseph Hergesheimer",
    "Lafcadio Hearn",
    "Kate Chopin",
    "Langston Hughes",
    "Louise Bogan",
    "Mark Twain",
    "Mary E. Wilkins Freeman",
    "Michael Gold",
    "Nathaniel Hawthorne",
    "Nella Larsen",
    "O. Henry",
    "Paul Laurence Dunbar",
    "Pauline E. Hopkins",
    "Ralph Adams Cram",
    "Robert Frost",
    "Robert W. Chambers",
    "Sara Teasdale",
    "Sarah Orne Jewett",
    "Sherwood Anderson",
    "Sinclair Lewis",
    "Stephen Crane",
    "Sutton E. Griggs",
    "T. S. Stribling",
    "Theodore Dreiser",
    "Thornton Wilder",
    "Upton Sinclair",
    "Vachel Lindsay",
    "Various (ed. Dorothy Scarborough)",
    "W. E. B. Du Bois",
    "Wallace Stevens",
    "Wallace Thurman",
    "Walt Whitman",
    "Washington Irving",
    "William Carlos Williams",
    "William Dean Howells",
    "Willa Cather",
    "Witter Bynner; Arthur Davison Ficke",
    "Zona Gale",
  ],
  "United Kingdom": [
    "A. E. Coppard",
    "A. E. Housman",
    "Aldous Huxley",
    "Alfred, Lord Tennyson",
    "Algernon Blackwood",
    "Algernon Charles Swinburne",
    "Amy Levy",
    "Arnold Bennett",
    "Arthur Conan Doyle",
    "Arthur Morrison",
    "Arthur Symons",
    "Charlotte Brontë",
    "Charlotte Mew",
    "Christina Rossetti",
    "D. H. Lawrence",
    "Dante Gabriel Rossetti",
    "David Lindsay",
    "Dorothy Richardson",
    "E. F. Benson",
    "E. G. Swain",
    "E. M. Forster",
    "E. Powys Mathers (tr.)",
    "Elizabeth Barrett Browning",
    "Elizabeth von Arnim",
    "Ford Madox Ford",
    "G. K. Chesterton",
    "Geoffrey Chaucer",
    "George Eliot",
    "George Gissing",
    "Grant Allen",
    "H. G. Wells",
    "H. Rider Haggard",
    "Harold Acton",
    "Hugh Clifford",
    "Israel Zangwill",
    "Jane Austen",
    "James Thomson (B.V.)",
    "John Galsworthy",
    "John Keats",
    "John Milton",
    "Joseph Conrad",
    "Lord Byron",
    "M. P. Shiel",
    "M. R. James",
    "Marie Belloc Lowndes",
    "Marie Corelli",
    "Mary Shelley",
    "Matthew Gregory Lewis",
    "May Sinclair",
    "Oliver Onions",
    "Rebecca West",
    "Richard Hughes",
    "Richard Marsh",
    "Robert Graves",
    "Robert Herrick",
    "Robert Hichens",
    "Rudyard Kipling",
    "Rose Macaulay",
    "Saki (H. H. Munro)",
    "Samuel Taylor Coleridge",
    "Siegfried Sassoon",
    "Sylvia Townsend Warner",
    "T. S. Eliot",
    "Thomas Burke",
    "Thomas Hardy",
    "Virginia Woolf",
    "W. Somerset Maugham",
    "William Gerhardie",
    "Walter de la Mare",
    "Wilfred Owen",
    "William Blake",
    "William Hope Hodgson",
    "William Morris",
    "Anne Brontë",
    "Charles Dickens",
    "Frank Swettenham",
  ],
  Ireland: [
    "Bram Stoker",
    "Charles Robert Maturin",
    "Ethel Lilian Voynich",
    "George Moore",
    "James Joyce",
    "James Stephens",
    "Joseph Sheridan Le Fanu",
    "Lord Dunsany",
    "Oscar Wilde",
    "Sarah Grand",
    "W. B. Yeats",
  ],
  Scotland: ["Norman Douglas", "Robert Louis Stevenson"],
  Wales: ["Arthur Machen"],
  France: [
    "Alain-Fournier",
    "Alexandre Dumas",
    "Alexandre Dumas fils",
    "Anatole France",
    "André Breton",
    "André Gide",
    "André Gide (tr. Dorothy Bussy)",
    "Arthur Rimbaud",
    "Charles Baudelaire",
    "Charles Baudelaire (tr. Arthur Symons)",
    "Charles Baudelaire (tr. Cyril Scott)",
    "Claude Farrère",
    "Colette",
    "Comte de Lautréamont",
    "Gaston Leroux",
    "Guillaume Apollinaire",
    "Gustave Flaubert",
    "Guy de Maupassant",
    "Henri Barbusse",
    "Honoré de Balzac",
    "Joris-Karl Huysmans",
    "Jean d'Esme",
    "Marcel Proust",
    "Octave Mirbeau",
    "Paul Verlaine (tr. Gertrude Hall)",
    "Pierre Choderlos de Laclos",
    "Pierre Loti",
    "Pierre Louÿs",
    "Romain Rolland",
    "Stendhal",
    "Tristan Corbière",
    "Victor Hugo",
    "Villiers de l'Isle-Adam",
    "Émile Nolly",
    "Émile Zola",
  ],
  Germany: [
    "Alfred Döblin",
    "E. T. A. Hoffmann",
    "Heinrich Heine",
    "Johann Wolfgang von Goethe",
    "Hermann Hesse",
    "Theodor Fontane",
    "Theodor Storm",
    "Thomas Mann",
  ],
  Austria: [
    "Arthur Schnitzler",
    "Joseph Roth",
    "Leopold von Sacher-Masoch",
    "Rainer Maria Rilke",
    "Rainer Maria Rilke (tr. Jessie Lemont)",
    "Vicki Baum",
  ],
  Russia: [
    "Aleksandr Kuprin",
    "Alexander Pushkin",
    "Andrei Bely",
    "Anton Chekhov",
    "Fyodor Dostoevsky",
    "Fyodor Sologub",
    "Isaac Babel",
    "Ivan Bunin",
    "Ivan Goncharov",
    "Ivan Turgenev",
    "Leonid Andreyev",
    "Leo Tolstoy",
    "Maxim Gorky",
    "Mikhail Artsybashev",
    "Mikhail Bulgakov",
    "Mikhail Lermontov",
    "Mikhail Saltykov-Shchedrin",
    "Nikolai Gogol",
    "Nikolai Leskov",
    "Various (ed. Thomas Seltzer)",
    "Vladimir Mayakovsky",
    "Yevgeny Zamyatin",
    "Yuri Olesha",
  ],
  Japan: [
    "Higuchi Ichiyō",
    "Jun'ichirō Tanizaki",
    "Matsuo Bashō",
    "Mori Ōgai",
    "Murasaki Shikibu",
    "Natsume Sōseki",
    "Ryūnosuke Akutagawa",
    "Yei Theodora Ozaki",
  ],
  China: [
    "Arthur Waley (tr.; Bai Juyi et al.)",
    "Cao Xueqin",
    "Liu E",
    "Lu Xun",
    "Luo Guanzhong",
    "Pu Songling",
    "Shi Nai'an",
    "Various (incl. Li Bai, Du Fu)",
    "Various (tr. Arthur Waley)",
    "Various (tr. L. Cranmer-Byng)",
    "Wu Cheng'en",
    "Wu Jingzi",
    "Zeng Pu",
    "Lanling Xiaoxiao Sheng",
  ],
  Italy: [
    "Alessandro Manzoni",
    "Antonio Fogazzaro",
    "Dante Alighieri",
    "Dante Alighieri (tr. Longfellow)",
    "Gabriele D'Annunzio",
    "Giacomo Leopardi (tr. Frederick Townsend)",
    "Giovanni Verga",
    "Grazia Deledda",
    "Italo Svevo",
    "Luigi Pirandello",
    "Ovid",
    "Virgil",
  ],
  Spain: [
    "Benito Pérez Galdós",
    "Emilia Pardo Bazán",
    "Federico García Lorca",
    "Leopoldo Alas (Clarín)",
    "Juan Valera",
    "Miguel de Unamuno",
    "Pío Baroja",
    "Ramón del Valle-Inclán",
    "Vicente Blasco Ibáñez",
    "Vicente Blasco Ibáñez (tr. Mrs. W. A. Gillespie)",
    "Víctor Català",
  ],
  Portugal: ["Camilo Castelo Branco", "Eça de Queirós", "Luís de Camões"],
  Brazil: [
    "Aluísio Azevedo",
    "José de Alencar",
    "Lima Barreto",
    "Machado de Assis",
    "Machado de Assis, Coelho Netto, Medeiros e Albuquerque, Carmen Dolores (tr. Isaac Goldberg)",
  ],
  Mexico: ["Federico Gamboa", "Mariano Azuela"],
  Argentina: ["José Hernández", "Roberto Arlt", "Ricardo Güiraldes"],
  Philippines: ["José Rizal", "José Rizal (tr. Charles Derbyshire)"],
  India: [
    "Bankim Chandra Chatterjee",
    "Bankim Chandra Chatterjee (tr. Miriam S. Knight)",
    "Bibhutibhushan Bandyopadhyay",
    "Kabir (tr. Rabindranath Tagore)",
    "Mayuram Vedanayagam Pillai",
    "Premchand",
    "Rabindranath Tagore",
    "Rabindranath Tagore (tr. Surendranath Tagore)",
    "Sarat Chandra Chattopadhyay",
    "Vālmīki (tr. Ralph T. H. Griffith)",
  ],
  Iran: [
    "Attar of Nishapur",
    "Ferdowsi",
    "Hafiz (tr. Gertrude Lowthian Bell)",
    "Jalal al-Din Rumi (ed./tr. F. Hadland Davis)",
    "Nizami",
    "Omar Khayyam (tr. Edward FitzGerald)",
  ],
  "South Africa": ["James A. Honey", "Olive Schreiner", "R. R. R. Dhlomo", "Sol Plaatje"],
  Australia: ["A. B. Paterson", "George Egerton", "Henry Handel Richardson", "Henry Lawson", "Joseph Furphy", "Marcus Clarke", "Miles Franklin", "Rolf Boldrewood"],
  "New Zealand": ["Katherine Mansfield"],
  Canada: ["Bliss Carman", "Frank L. Packard", "Louis Hémon", "Onoto Watanna (Winnifred Eaton)", "Robert W. Service"],
  Jamaica: ["Claude McKay", "Martha Warren Beckwith", "Walter Jekyll"],
  Guyana: ["Eric Walrond"],
  Hungary: ["Dezső Kosztolányi", "Ferenc Molnár", "Kálmán Mikszáth", "Mór Jókai"],
  Czechia: ["Franz Kafka", "Gustav Meyrink", "Jaroslav Hašek", "Karel Čapek"],
  Poland: [
    "Adam Mickiewicz",
    "Bolesław Prus",
    "Henryk Sienkiewicz",
    "I. L. Peretz",
    "Sholem Asch",
    "Various (tr. Else C. M. Benecke et al.)",
    "Various (tr. Helena Frank)",
    "Władysław Reymont",
  ],
  Netherlands: ["Louis Couperus", "Multatuli"],
  Belgium: [
    "Georges Rodenbach",
    "Maurice Maeterlinck (tr. Bernard Miall)",
    "Émile Verhaeren (tr. Alma Strettell)",
  ],
  Sweden: ["August Strindberg", "Selma Lagerlöf"],
  Norway: ["Alexander Kielland", "Bjørnstjerne Bjørnson", "Henrik Ibsen", "Jonas Lie", "Knut Hamsun", "Knut Hamsun (tr. W. W. Worster)", "Sigrid Undset"],
  Denmark: ["Henrik Pontoppidan", "J. P. Jacobsen", "Jens Peter Jacobsen", "Martin Andersen Nexø"],
  Finland: ["Aleksis Kivi", "Elias Lönnrot", "Johannes Linnankoski"],
  Greece: [
    "Alexandros Papadiamantis",
    "C. P. Cavafy",
    "Sappho (ed./tr. Henry Thornton Wharton)",
  ],
  Turkey: ["Halide Edib Adıvar"],
  Ukraine: ["Lesya Ukrainka", "Mykhailo Kotsiubynsky", "Sholem Aleichem"],
  Romania: ["Liviu Rebreanu", "Mateiu Caragiale", "Various (tr. Lucy Byng)"],
  Korea: ["Yi Kwang-su"],
  Egypt: ["Muhammad Husayn Haykal", "Ibn Tufail"],
  Lebanon: ["Ameen Rihani", "Kahlil Gibran"],
  Malaysia: [
    "Abdullah bin Abdul Kadir; tr. W. G. Shellabear",
    "Anonymous Malay court chronicle; tr. John Leyden",
    "Frank Swettenham",
    "Hugh Clifford",
  ],
  Thailand: ["Anonymous Siamese; tr. J. Crosby"],
  Laos: ["Katherine Neville Fleeson"],
  Vietnam: ["Nguyễn Du; ed./tr. Abel des Michels"],
  Indonesia: [
    "Raden Adjeng Kartini",
    "Raden Adjeng Kartini (tr. Agnes Louise Symmers)",
  ],
  Ghana: ["W. H. Barker and Cecilia Sinclair"],
  Peru: ["Ricardo Palma"],
  Venezuela: ["Rómulo Gallegos", "Teresa de la Parra"],
  Colombia: ["Jorge Isaacs", "José Eustasio Rivera"],
  Uruguay: ["Horacio Quiroga", "W. H. Hudson"],
  Guatemala: ["Miguel Ángel Asturias"],
  Nicaragua: ["Rubén Darío"],
  Cuba: ["Cirilo Villaverde"],
  Belarus: ["Mendele Mocher Sforim", "S. An-sky"],
  Palestine: ["Yosef Haim Brenner"],
  Iraq: ["Anonymous (Mesopotamian)"],
  Israel: ["Anonymous (Hebrew Bible)"],
};

/** Per-work when author/language would name the wrong country. */
const WORK_COUNTRY: Record<string, string> = {
  // Adapted by Salon remakes (Salon original text; US settings)
  "miss-brill-adapted": "United States",
  "prefer-not": "United States",
  "late-season": "United States",
  "between-the-drop-and-the-water": "United States",
  "he-woke-changed": "United States",
  "the-pattern": "United States",
  "a-coat-worthy-of-respect": "United States",
  "what-she-borrowed": "United States",
  "it-was-not-nervousness": "United States",
  "during-carnival": "United States",
  "what-we-sold": "United States",
  // English-language translations / binds of foreign originals
  basilio: "Portugal",
  "bel-ami": "France",
  botchan: "Japan",
  cheri: "France",
  liliom: "Hungary",
  "the-cherry-orchard": "Russia",
  magnhild: "Norway",
  "the-family-at-gilje": "Norway",
  "after-the-divorce": "Italy",
  "colonel-chabert": "France",
  "the-black-tulip": "France",
  "the-man-who-was-afraid": "Russia",
  "poems-in-prose": "France",
  "poems-hot-houses-bernard-miall": "Belgium",
  "poems-of-emile-verhaeren": "Belgium",
  "poems-jessie-lemont-translation": "Austria",
  "the-rubaiyat-of-omar-khayyam": "Iran",
  "songs-of-kabir": "India",
  gitanjali: "India",
  "post-office": "India",
  rur: "Czechia",
  underdogs: "Mexico",
  madmen: "Argentina",
  naomi: "Japan",
  odessa: "Ukraine",
  we: "Russia",
  berlin: "Germany",
  vengeance: "Poland",
  "miss-julie": "Sweden",
  // Hearn: Louisiana vs Japan
  "kwaidan-stories-and-studies-of-strange-things": "Japan",
  "chita-a-memory-of-last-island": "United States",
  "some-chinese-ghosts": "China",
  "in-ghostly-japan": "Japan",
  shadowings: "Japan",
  // McKay
  banjo: "France",
  "harlem-shadows": "United States",
  "home-harlem": "United States",
  "constab-ballads": "Jamaica",
  // Kipling — the Indian books
  kim: "India",
  "plain-tales-from-the-hills": "India",
  "life-s-handicap-being-stories-of-mine-own-people": "India",
  "the-phantom-rickshaw-and-other-ghost-stories": "India",
  "actions-and-reactions": "India",
  "soldiers-three": "India",
  "nada-the-lily": "South Africa",
  "the-painted-veil": "United Kingdom",
  "the-good-soldier": "United Kingdom",
  "growth-of-the-soil": "Norway",
  // Folklore / anonymous / compiled
  njala: "Iceland",
  nights: "Egypt",
  // Old English poem; narrative is Denmark/Geatland. Chip England
  // (literary language/origin) rather than invent a North Sea city.
  beowulf: "United Kingdom",
  "the-nibelungenlied": "Germany",
  "laxd-la-saga": "Iceland",
  "song-of-songs": "Israel",
  "malay-annals-sejarah-melayu": "Malaysia",
  "the-story-of-grettir-the-strong": "Iceland",
  "the-book-of-the-birds-paksi-pakaranam": "Thailand",
  "the-epic-of-gilgamesh": "Iraq",
  "the-poetic-edda": "Iceland",
  "jamaican-song-and-story": "Jamaica",
  "jamaica-anansi-stories": "Jamaica",
  "high-wind-jamaica": "Jamaica",
  "noli-me-tangere": "Philippines",
  vera: "United Kingdom",
  "on-a-chinese-screen": "United Kingdom",
  futility: "United Kingdom",
  "poison-tree": "India",
  "trooper-peter-halket": "South Africa",
  "south-african-folk-tales": "South Africa",
  "west-african-folk-tales": "Ghana",
  "laos-folk-lore-of-farther-india": "Laos",
  "japanese-fairy-tales": "Japan",
  hayy: "Spain",
  "african-farm": "South Africa",
  mhudi: "South Africa",
  "an-african-tragedy": "South Africa",
  tropic: "Guyana",
  "the-purple-land": "Uruguay",
  // Hudson wrote from Uruguay; Green Mansions is Guiana jungle, not the Banda Oriental.
  "green-mansions": "Guyana",
  // Pastoral utopia in a future English countryside, not Uruguay.
  "a-crystal-age": "United Kingdom",
  "maria-chapdelaine": "Canada",
  cathay: "China",
  kalevala: "Finland",
  "the-ramayan-of-valmiki": "India",
  "letters-of-a-javanese-princess": "Indonesia",
  "kim-van-kieu-tan-truyen-the-tale-of-kieu": "Vietnam",
  "a-japanese-nightingale": "Canada",
  "under-fire": "France",
  "the-literature-of-arabia": "Iraq",
  "the-garden-of-bright-waters": "Iraq",
  "more-translations-from-the-chinese": "China",
  "a-hundred-and-seventy-chinese-poems": "China",
  "three-hundred-tang-poems": "China",
  "a-lute-of-jade": "China",
  "roumanian-stories": "Romania",
  "best-russian-short-stories": "Russia",
  "selected-polish-tales": "Poland",
  "yiddish-tales": "Poland",
  "brazilian-tales": "Brazil",
  dybbuk: "Ukraine",
  fishke: "Belarus",
  tevye: "Ukraine",
  bontshe: "Poland",
  metamorphosis: "Czechia",
  golem: "Czechia",
  venice: "Germany",
  siddhartha: "Germany",
  "grand-hotel": "Austria",
  "dream-story": "Austria",
  "heartless": "Korea",
  zaynab: "Egypt",
  breakdown: "Palestine",
  "forest-song": "Ukraine",
  shadows: "Ukraine",
  maria: "Colombia",
  vortex: "Colombia",
  iphigenia: "Venezuela",
  barbara: "Venezuela",
  "mama-blanca": "Venezuela",
  guatemala: "Guatemala",
  "don-segundo-sombra": "Argentina",
  "tradiciones-peruanas": "Peru",
  quiroga: "Uruguay",
  cecilia: "Cuba",
  santa: "Mexico",
  solitude: "Spain",
  cubas: "Brazil",
  "attendants-confession": "Brazil",
  casmurro: "Brazil",
  quincas: "Brazil",
  slum: "Brazil",
  policarpo: "Brazil",
  amaro: "Portugal",
  maias: "Portugal",
  "cousin-basilio": "Portugal",
  ramires: "Portugal",
  "os-lusiadas": "Portugal",
  "amor-de-perdicao": "Portugal",
  "hidden-force": "Netherlands",
  havelaar: "Netherlands",
  "max-havelaar": "Netherlands",
  "seven-brothers": "Finland",
  "niels": "Denmark",
  "marie-grubbe": "Denmark",
  "lucky-per": "Denmark",
  "pelle-the-conqueror": "Denmark",
  hunger: "Norway",
  pan: "Norway",
  jenny: "Norway",
  kristin: "Norway",
  ghosts: "Norway",
  "skipper-worse": "Norway",
  gosta: "Sweden",
  doll: "Poland",
  "pan-tadeusz": "Poland",
  "the-peasants": "Poland",
  ion: "Romania",
  "forest-hanged": "Romania",
  "the-rakes-of-the-old-court": "Romania",
  svejk: "Czechia",
  skylark: "Hungary",
  handan: "Turkey",
  "murderess": "Greece",
  "poems-lifetime-pamphlets": "Greece",
  cat: "Japan",
  genji: "Japan",
  kokoro: "Japan",
  "wild-geese": "Japan",
  rashomon: "Japan",
  "vita-sexualis": "Japan",
  "growing-up": "Japan",
  "call-to-arms": "China",
  "red-chamber": "China",
  "water-margin": "China",
  "journey-west": "China",
  "jin-ping-mei": "China",
  "strange-tales": "China",
  scholars: "China",
  "lao-can": "China",
  "flower-sin": "China",
  shahnameh: "Iran",
  conference: "Iran",
  layla: "Iran",
  anandamath: "India",
  "chokher-bali": "India",
  gora: "India",
  "home-world": "India",
  "the-home-and-the-world": "India",
  "the-immoralist": "France",
  "blood-and-sand": "Spain",
  ecstasy: "Netherlands",
  "an-outcast-of-the-islands": "United Kingdom",
  "the-underdogs": "Mexico",
  "diary-of-a-chambermaid": "France",
  devdas: "India",
  sevasadan: "India",
  rangbhoomi: "India",
  nirmala: "India",
  prathapa: "India",
  "pather-panchali": "India",
  "ulysses": "Ireland",
  dubliners: "Ireland",
  "a-portrait-of-the-artist-as-a-young-man": "Ireland",
  dorian: "Ireland",
  dracula: "Ireland",
  "the-purple-cloud": "United Kingdom",
  "she": "United Kingdom",
  "the-light-that-failed": "United Kingdom",
  "pictures-of-the-floating-world": "United States",
  "the-prophet": "Lebanon",
  "the-madman-his-parables-and-poems": "Lebanon",
  "the-forerunner-his-parables-and-poems": "Lebanon",
  "the-book-of-khalid": "Lebanon",
  "my-brilliant-career": "Australia",
  "the-getting-of-wisdom": "Australia",
  "for-the-term-of-his-natural-life": "Australia",
  "the-man-from-snowy-river": "Australia",
  "robbery-under-arms": "Australia",
  "in-a-german-pension": "New Zealand",
  "bliss-and-other-stories": "New Zealand",
  "the-garden-party-and-other-stories": "New Zealand",
  "the-house-of-pride-and-other-tales-of-hawaii": "United States",
  "island-tales-on-the-makaloa-mat": "United States",
  "lost-face": "United States",
  "when-god-laughs-and-other-stories": "United States",
  "the-night-born": "United States",
  "before-adam": "United States",
  "the-scarlet-plague": "United States",
  "free-air": "United States",
  "looking-backward": "United States",
  "poor-white": "United States",
  "vandover-and-the-brute": "United States",
  "alexander-s-bridge": "United States",
  "my-mortal-enemy": "United States",
  "iola-leroy": "United States",
  "the-sport-of-the-gods": "United States",
  "war-is-kind": "United States",
  "fifty-years-other-poems": "United States",
  "spectra-a-book-of-poetic-experiments": "United States",
  "black-spirits-and-white-a-book-of-ghost-stories": "United States",
  "strictly-business-more-stories-of-the-four-million": "United States",
  "fantastic-fables": "United States",
  "poems-wilfred-owen": "United Kingdom",
  "counter-attack-and-other-poems": "United Kingdom",
  "picture-show": "United Kingdom",
  "the-pier-glass": "United Kingdom",
  "country-sentiment": "United Kingdom",
  "responsibilities-and-other-poems": "Ireland",
  "the-green-helmet-and-other-poems": "Ireland",
  reincarnations: "Ireland",
  "the-stoneground-ghost-tales": "United Kingdom",
  "heart-of-darkness": "United Kingdom",
};

const AUTHOR_COUNTRY: Record<string, string> = (() => {
  const out: Record<string, string> = {};
  for (const [country, authors] of Object.entries(AUTHORS_BY_COUNTRY)) {
    for (const author of authors) out[author] = country;
  }
  return out;
})();

const CITY_LABELS = new Set([
  "London",
  "New York",
  "Dublin",
  "Sydney",
  "Delhi",
  "Paris",
  "Moscow",
  "Madrid",
  "Mexico City",
  "Buenos Aires",
  "Berlin",
  "Tokyo",
  "Beijing",
  "Lisbon",
  "Rio",
  "Kolkata",
  "Rome",
  "Amsterdam",
  "Warsaw",
  "Stockholm",
  "Oslo",
  "Tehran",
  "Budapest",
  "Cairo",
  "Copenhagen",
  "Athens",
  "Bucharest",
  "Prague",
  "Helsinki",
  "Kyiv",
  "Jerusalem",
  "Reykjavík",
  "Chennai",
  "Barcelona",
  "Elsewhere",
]);

export function countryFor(work: Pick<ShelfWork, "id" | "author" | "language">): string {
  const fromWork = WORK_COUNTRY[work.id];
  if (fromWork) return fromWork;
  const fromAuthor = AUTHOR_COUNTRY[work.author];
  if (fromAuthor) return fromAuthor;
  const fromLang = LANG_COUNTRY[work.language];
  if (fromLang) return fromLang;
  return "";
}

export function isCityHubLabel(label: string) {
  return CITY_LABELS.has(label);
}
