import { countryFor } from "./countries.ts";
import { FEATURED_CAROUSEL_IDS } from "./pitches.ts";
import { ADAPTED_BY_SALON_IDS, NEXT_FEATURED_TRACK_IDS } from "./curatorial.ts";
import { RITUAL_LANES } from "./rituals.ts";
import { shelfWork, type ShelfWork } from "./shelf.ts";
import { REGION_SHAPES, type PlaceRegion } from "./region-shapes.ts";

/**
 * Reader-facing place of setting (or “from”) — not author origin and not
 * the Map’s language hubs. Short label + ISO-ish region for a silhouette.
 *
 * Resolution: per-work setting → country-of-origin fallback → omit.
 * Unknown / unplaceable works stay off chrome rather than inventing a city.
 */
export type WorkPlace = {
  label: string;
  region: PlaceRegion;
};

export type PlaceRef = Pick<ShelfWork, "id" | "author" | "language">;

/** Curated setting labels for locked recommend, Next, ritual lanes, and named examples. */
const WORK_PLACE: Record<string, WorkPlace> = {
  // Named examples / other local binds
  vengeance: { label: "Poland", region: "pl" },
  passing: { label: "Harlem", region: "us" },
  we: { label: "One State / glass city", region: "ru" },
  berlin: { label: "Berlin", region: "de" },
  manhattan: { label: "New York", region: "us" },
  crime: { label: "Petersburg", region: "ru" },
  dorian: { label: "London", region: "gb" },
  bovary: { label: "France", region: "fr" },
  odessa: { label: "Odessa", region: "ua" },
  naomi: { label: "Tokyo", region: "jp" },
  dracula: { label: "Transylvania", region: "ro" },
  gold: { label: "New York", region: "us" },

  // Locked recommend order (live front door)
  "enchanted-april": { label: "Italy", region: "it" },
  "the-bridge-of-san-luis-rey": { label: "Peru", region: "pe" },
  "mr-fortunes-maggot": { label: "Fanua", region: "ws" },
  "the-house-of-mirth": { label: "New York", region: "us" },
  quicksand: { label: "Naxos / South", region: "us-south" },

  // Next / priority Host-a-sit queue
  basilio: { label: "Lisbon", region: "pt" },
  blacker: { label: "Harlem", region: "us" },
  "a-lost-lady": { label: "Sweet Water", region: "us" },
  "the-wanderer": { label: "Sainte-Agathe", region: "fr" },
  "the-cabala": { label: "Rome", region: "it" },
  "reuben-sachs": { label: "Lancaster Gate", region: "gb" },
  "the-late-mattia-pascal": { label: "Miragno", region: "it" },
  "lady-macbeth": { label: "Mtsensk", region: "ru" },
  summer: { label: "North Dormer", region: "us" },
  "jacob-s-room": { label: "Cornwall", region: "gb" },
  "the-tenant-of-wildfell-hall": { label: "Yorkshire", region: "gb" },
  "the-last-man": { label: "England", region: "gb" },
  oblomov: { label: "Petersburg", region: "ru" },
  "the-lady-with-the-dog-and-other-stories": { label: "Yalta", region: "ru" },
  zeno: { label: "Trieste", region: "it" },
  "the-book-of-khalid": { label: "Baalbek", region: "lb" },
  "attendants-confession": { label: "Brazil", region: "br" },
  rashomon: { label: "Kyoto / Japan", region: "jp" },
  "high-wind-jamaica": { label: "Jamaica", region: "jm" },
  "noli-me-tangere": { label: "Manila", region: "ph" },
  vera: { label: "Cornwall", region: "gb" },
  "on-a-chinese-screen": { label: "China", region: "cn" },
  futility: { label: "Simbirsk", region: "ru" },
  "poison-tree": { label: "Bengal", region: "in" },
  "trooper-peter-halket": { label: "Mashonaland", region: "za" },
  "the-home-and-the-world": { label: "Bengal", region: "in" },
  "the-hidden-force": { label: "Labuwangi", region: "id" },
  hunger: { label: "Kristiania", region: "no" },
  "jude-the-obscure": { label: "Marygreen", region: "gb" },
  "the-moon-and-sixpence": { label: "England → Tahiti", region: "gb" },
  "my-brilliant-career": { label: "Australia — Possum Gully", region: "au" },
  "the-plumed-serpent": { label: "Mexico City", region: "mx" },
  "the-red-room": { label: "Stockholm", region: "se" },
  "the-green-carnation": { label: "London — Piccadilly", region: "gb" },
  "hajji-baba": { label: "Ispahan", region: "ir" },
  "the-master-of-ballantrae": { label: "Durrisdeer", region: "gb" },
  "a-set-of-six": { label: "Chile", region: "cl" },
  "the-hill-of-dreams": { label: "Wales — Gwent", region: "gb" },
  "the-story-of-an-african-farm": { label: "Karoo", region: "za" },
  "the-imperialist": { label: "Elgin, Ontario", region: "ca" },
  "mogens-and-other-stories": { label: "Denmark", region: "dk" },
  "the-road-to-the-open": { label: "Vienna", region: "at" },
  calvary: { label: "Orne", region: "fr" },
  "anna-of-the-five-towns": { label: "Five Towns — Potteries", region: "gb" },
  "small-souls": { label: "The Hague", region: "nl" },
  "stories-and-pictures": { label: "Yiddish Pale", region: "pl" },
  "white-jacket": { label: "Callao", region: "pe" },
  "a-japanese-nightingale": { label: "Japan — bay", region: "jp" },
  "maria-chapdelaine": { label: "Peribonka", region: "ca" },
  "the-house-by-the-medlar-tree": { label: "Trezza, Sicily", region: "it" },
  "filipino-popular-tales": { label: "Pampanga", region: "ph" },
  "the-marrow-of-tradition": { label: "Wilmington", region: "us-south" },
  "zuleika-dobson": { label: "Oxford", region: "gb" },
  "eugenie-grandet": { label: "Saumur", region: "fr" },
  "laos-folk-lore": { label: "Laos", region: "la" },
  "born-in-exile": { label: "Kingsmill", region: "gb" },
  "the-four-horsemen-of-the-apocalypse": { label: "Buenos Aires", region: "ar" },
  "virgin-soil": { label: "St Petersburg", region: "ru" },
  "the-immoralist": { label: "France", region: "fr" },
  "where-angels-fear-to-tread": { label: "Charing Cross → Tuscany", region: "it" },
  "the-man-of-property": { label: "Stanhope Gate", region: "gb" },
  "theresa-raquin": { label: "Pont Neuf", region: "fr" },
  "the-gadfly": { label: "Pisa", region: "it" },
  "letters-of-a-javanese-princess": { label: "Java — Japara", region: "id" },
  "blood-and-sand": { label: "Madrid", region: "es" },
  ecstasy: { label: "The Hague / Scheveningen", region: "nl" },
  "an-outcast-of-the-islands": { label: "Malay Archipelago", region: "id" },
  "the-underdogs": { label: "Mexico — sierra", region: "mx" },
  "diary-of-a-chambermaid": { label: "Paris", region: "fr" },
  "the-painted-veil": { label: "Hong Kong orbit", region: "cn" },
  "the-good-soldier": { label: "Nauheim", region: "de" },
  "une-vie": { label: "Normandy", region: "fr" },
  "crime-and-punishment": { label: "Petersburg", region: "ru" },
  "uncle-silas": { label: "Bartram-Haugh", region: "ie" },
  "rise-of-david-levinsky": { label: "Lower East Side", region: "us" },
  "for-the-term-of-his-natural-life": { label: "Prison Ship", region: "au" },
  "bottle-imp": { label: "Hawaii", region: "ws" },
  "death-in-venice": { label: "Venice", region: "it" },
  "elmer-gantry": { label: "Cato", region: "us" },
  "colonels-dream": { label: "Clarendon", region: "us-south" },
  "hard-times": { label: "Coketown", region: "gb" },
  "great-god-pan": { label: "London", region: "gb" },
  manalive: { label: "Beacon House", region: "gb" },
  "captain-blood": { label: "Caribbean", region: "bb" },
  "the-monomaniac": { label: "Le Havre railway", region: "fr" },
  "tartarin-de-tarascon": { label: "Algeria", region: "dz" },
  "the-time-machine": { label: "Richmond", region: "gb" },
  "prisoner-of-zenda": { label: "Strelsau", region: "at" },
  kidnapped: { label: "Highlands", region: "gb" },
  "revolt-of-the-angels": { label: "St. Sulpice", region: "fr" },
  "children-of-the-soil": { label: "Kremen", region: "pl" },
  "the-invisible-man": { label: "Iping", region: "gb" },
  "the-village-in-the-jungle": { label: "Beddagama, Ceylon", region: "lk" },
  "the-joy-of-captain-ribot": { label: "Valencia", region: "es" },
  saracinesca: { label: "Rome", region: "it" },
  "the-torrents-of-spring": { label: "Frankfort", region: "de" },
  "the-bet": { label: "Russia", region: "ru" },
  "the-bitter-tea-of-general-yen": { label: "Shanghai", region: "cn" },
  "the-woman-of-andros": { label: "Brynos", region: "gr" },
  "bella-donna": { label: "London → Egypt", region: "eg" },
  "nina-balatka": { label: "Prague", region: "cz" },
  "la-lupa": { label: "Sicily", region: "it" },
  "a-farewell-to-arms": { label: "Italy", region: "it" },
  "alice-adams": { label: "US Midwest", region: "us" },
  "quartet": { label: "Paris", region: "fr" },
  "song-of-songs-sudermann": { label: "Germany → Berlin", region: "de" },
  "its-wavering-image": { label: "San Francisco (Chinatown)", region: "us" },
  "java-head": { label: "Salem", region: "us" },
  "sunshine-sketches-of-a-little-town": { label: "Mariposa", region: "ca" },
  "guest-the-one-eyed": { label: "Borg", region: "is" },
  "the-blind-musician": { label: "Volhynia", region: "ua" },
  "magnolia-flower": { label: "St. Johns River", region: "us-south" },
  "in-the-mountains": { label: "Mountainside chalet, Switzerland", region: "ch" },
  "the-two-countesses": { label: "Sebenberg Castle and Vienna", region: "at" },
  "el-ombu": { label: "Pampas near Chascomús", region: "ar" },
  "halil-the-pedlar": { label: "Istanbul", region: "tr" },
  "the-white-sand-path": { label: "West Flanders village", region: "be" },
  "liliecronas-home": { label: "Värmland, Sweden", region: "se" },
  "doctor-luke-of-the-labrador": { label: "Labrador coast", region: "ca" },
  "morrina": { label: "Madrid, Spain", region: "es" },
  "a-happy-boy": { label: "Norway", region: "no" },
  "the-desjardins": { label: "Viger, Quebec", region: "ca" },
  "gone-to-earth": { label: "Welsh border hills", region: "gb" },
  "the-real-charlotte": { label: "Dublin & Lismoyle, Ireland", region: "ie" },
  "pembroke": { label: "Pembroke, New England", region: "us" },
  "the-argonauts": { label: "Poland", region: "pl" },
  "at-the-roadside-station": { label: "Russia", region: "ru" },
  "look-back-on-happiness": { label: "Norway forest", region: "no" },
  "father-of-yoto": { label: "Limehouse", region: "gb" },
  "growth-of-the-soil": { label: "Norway", region: "no" },
  "nada-the-lily": { label: "Zululand", region: "za" },
  "all-quiet-on-the-western-front": { label: "Western Front", region: "fr" },
  "the-story-of-gosta-berling": { label: "Sweden — Värmland", region: "se" },
  thais: { label: "Egypt — Thebaid / Nile", region: "eg" },
  demian: { label: "Germany — little-town Latin school", region: "de" },
  "death-comes-for-the-archbishop": { label: "New Mexico — arid red hills", region: "us" },
  "the-getting-of-wisdom": { label: "Australia — Melbourne orbit", region: "au" },
  bliss: { label: "London", region: "gb" },
  "a-hundred-and-seventy-chinese-poems": { label: "China", region: "cn" },
  "martin-bircks-youth": { label: "Stockholm", region: "se" },
  steppenwolf: { label: "Basel / Germany", region: "de" },
  shadowings: { label: "Japan", region: "jp" },
  "brazilian-tales": { label: "Rio — Guarda-Velha", region: "br" },
  "nacha-regules": { label: "Buenos Aires", region: "ar" },
  krakatit: { label: "Prague", region: "cz" },
  "the-peasants": { label: "Poland village", region: "pl" },
  cane: { label: "Georgia", region: "us-south" },
  "a-hero-of-our-time": { label: "Caucasus—Georgia", region: "ge" },
  "strange-tales": { label: "China", region: "cn" },
  "short-stories-from-the-balkans": { label: "Romania", region: "ro" },
  "the-awakening": { label: "Grand Isle", region: "us-south" },
  tropic: { label: "Barbados", region: "bb" },
  "there-is-confusion": { label: "New York / Richmond", region: "us" },
  "pointed-roofs": { label: "Hanover", region: "de" },
  "the-rise-of-silas-lapham": { label: "Boston", region: "us" },
  indiana: { label: "Brie", region: "fr" },
  "the-book-of-wonder": { label: "Shepperalk", region: "ie" },
  buddenbrooks: { label: "Lübeck", region: "de" },
  "miss-lulu-bett": { label: "Midwest", region: "us" },
  "the-sport-of-the-gods": { label: "Oakley", region: "us-south" },
  ramuntcho: { label: "Bidassoa", region: "fr" },
  "the-pit": { label: "Chicago", region: "us" },
  reginald: { label: "London", region: "gb" },
  "royal-highness": { label: "Albrechtstrasse", region: "de" },
  ramona: { label: "Moreno Mission", region: "us" },
  "almayers-folly": { label: "Pantai", region: "id" },
  "the-crux": { label: "Margate", region: "us" },
  "the-black-dog": { label: "England village", region: "gb" },
  "daisy-miller": { label: "Vevey", region: "ch" },
  "south-wind": { label: "Nepenthe", region: "it" },
  "the-village": { label: "Durnovka", region: "ru" },
  "ditte-girl-alive": { label: "Denmark", region: "dk" },
  "flappers-and-philosophers": { label: "Country club", region: "us" },
  "candide": { label: "Westphalia", region: "de" },
  "iola-leroy": { label: "US South", region: "us-south" },
  "esther-waters": { label: "England", region: "gb" },
  "aphrodite": { label: "Alexandria", region: "eg" },
  "west-african-folk-tales": { label: "Gold Coast", region: "gh" },
  erewhon: { label: "New Zealand", region: "nz" },
  "ann-veronica": { label: "Morningside Park", region: "gb" },
  "the-great-hunger": { label: "Norway fjord", region: "no" },
  "the-mysterious-stranger": { label: "Eseldorf", region: "at" },
  "children-of-the-frost": { label: "Yukon", region: "ca" },
  "the-poison-tree": { label: "Bengal", region: "in" },
  cosmopolis: { label: "Rome", region: "it" },
  "the-woman-who-did": { label: "Surrey", region: "gb" },
  "billy-budd": { label: "British man-of-war", region: "gb" },
  "malay-sketches": { label: "Malaya", region: "my" },
  "cousin-betty": { label: "Paris", region: "fr" },
  "the-sorrows-of-satan": { label: "England", region: "gb" },
  "the-king-of-schnorrers": { label: "London Sephardi", region: "gb" },
  hania: { label: "Poland", region: "pl" },
  "the-toys-of-peace": { label: "England", region: "gb" },
  "tess-of-the-durbervilles": { label: "Wessex", region: "gb" },
  "captains-courageous": { label: "Grand Banks", region: "ca" },
  "numa-roumestan": { label: "Provence", region: "fr" },
  "the-tug-of-love": { label: "Jewish workshop", region: "gb" },
  "the-house-of-the-seven-gables": { label: "Salem", region: "us" },
  "heart-of-darkness": { label: "Congo river", region: "cd" },
  "toilers-of-the-sea": { label: "Guernsey", region: "fr" },
  "indian-summer": { label: "Florence", region: "it" },
  "a-slav-soul": { label: "Russia", region: "ru" },
  "cabbages-and-kings": { label: "Anchuria", region: "gt" },
  "picture-of-dorian-gray": { label: "London", region: "gb" },
  "the-job": { label: "Panama, Pennsylvania", region: "us" },
  "reign-of-greed": { label: "Pasig", region: "ph" },
  "a-cross-line": { label: "England", region: "gb" },
  "shadow-of-the-cathedral": { label: "Toledo", region: "es" },
  "way-of-all-flesh": { label: "England", region: "gb" },
  "family-at-gilje": { label: "Norway", region: "no" },
  resurrection: { label: "Russia", region: "ru" },
  widdershins: { label: "England", region: "gb" },
  typee: { label: "Marquesas", region: "ws" },
  kangaroo: { label: "Sydney", region: "au" },
  "casanovas-homecoming": { label: "Vienna", region: "at" },
  "the-mother": { label: "Sardinia", region: "it" },
  "lord-arthur-saviles-crime": { label: "England", region: "gb" },
  "three-soldiers": { label: "France WWI", region: "fr" },
  "doctor-pascal": { label: "Plassans", region: "fr" },
  "in-the-world": { label: "Russia", region: "ru" },
  leila: { label: "Italy", region: "it" },
  charan: { label: "Korea", region: "kr" },
  "antic-hay": { label: "Postwar London", region: "gb" },
  "spring-time-case": { label: "Yeddo", region: "jp" },
  "eline-vere": { label: "The Hague", region: "nl" },
  "hungry-stones": { label: "Bengal", region: "in" },
  smoke: { label: "Baden-Baden", region: "de" },
  "niels-lyhne": { label: "Jutland", region: "dk" },
  "the-emancipated": { label: "Posillipo", region: "it" },
  germinal: { label: "Montsou", region: "fr" },
  "our-lady-of-the-pillar": { label: "Segovia", region: "es" },
  kipps: { label: "New Romney", region: "gb" },
  "the-professor": { label: "Brussels", region: "be" },
  "martin-eden": { label: "Oakland", region: "us" },
  "madame-heurtebise": { label: "Paris", region: "fr" },
  color: { label: "US lyric", region: "us" },

  // Named examples
  botchan: { label: "Tokyo", region: "jp" },
  silhouettes: { label: "Dieppe", region: "fr" },
  "a-room-with-a-view": { label: "Florence", region: "it" },

  // Ritual lanes (beyond locked recommend / Next)
  "bunner-sisters": { label: "New York", region: "us" },
  "the-weary-blues": { label: "Harlem", region: "us" },
  "kwaidan-stories-and-studies-of-strange-things": { label: "Japan", region: "jp" },
  carmilla: { label: "Styria", region: "at" },
  "hungry-hearts": { label: "Lower East Side", region: "us" },
  "in-our-time": { label: "Michigan", region: "us" },
  "the-wild-swans-at-coole": { label: "Ireland", region: "ie" },
  "the-listeners-and-other-poems": { label: "England", region: "gb" },
  "the-empty-house-and-other-ghost-stories": { label: "England", region: "gb" },
  "dark-of-the-moon": { label: "United States", region: "us" },
  "love-songs": { label: "United States", region: "us" },
  "the-house-of-souls": { label: "London", region: "gb" },
  wallpaper: { label: "United States", region: "us" },
  "the-rubaiyat-of-omar-khayyam": { label: "Persia", region: "ir" },
  "spring-and-all": { label: "United States", region: "us" },
  "a-few-figs-from-thistles": { label: "United States", region: "us" },
  "songs-of-innocence-and-of-experience": { label: "England", region: "gb" },
  "second-april": { label: "United States", region: "us" },
  "renascence-and-other-poems": { label: "United States", region: "us" },
  "mountain-interval": { label: "New England", region: "us" },
  gitanjali: { label: "Bengal", region: "in" },
  "songs-of-kabir": { label: "India", region: "in" },
  "pictures-of-the-floating-world": { label: "Japan", region: "jp" },
  "the-garden-party-and-other-stories": { label: "Crescent Bay", region: "nz" },
  "trooper-peter-halket-of-mashonaland": { label: "Mashonaland", region: "za" },
  "bliss-and-other-stories": { label: "New Zealand", region: "nz" },
  "body-of-this-death": { label: "United States", region: "us" },
  orlando: { label: "England", region: "gb" },
  cheri: { label: "Paris", region: "fr" },
  dalloway: { label: "London", region: "gb" },
  "north-of-boston": { label: "New England", region: "us" },
  "chicago-poems": { label: "Chicago", region: "us" },
  "harlem-shadows": { label: "Harlem", region: "us" },
  "sour-grapes": { label: "United States", region: "us" },
  precipitations: { label: "New York", region: "us" },
  "flame-and-shadow": { label: "United States", region: "us" },
  "helen-of-troy-and-other-poems": { label: "United States", region: "us" },
  "spoon-river-anthology": { label: "Illinois", region: "us" },
  "copper-sun": { label: "United States", region: "us" },
  "the-black-christ-and-other-poems": { label: "United States", region: "us" },

  // Frequent shelf settings (pitches / serialize) — still not invented cities
  banjo: { label: "Marseille", region: "fr" },
  "the-sun-also-rises": { label: "Paris → Pamplona", region: "fr" },
  gatsby: { label: "New York", region: "us" },
  "the-age-of-innocence": { label: "New York", region: "us" },
  "liza-of-lambeth": { label: "London", region: "gb" },
  "a-passage-to-india": { label: "India", region: "in" },
  "lolly-willowes": { label: "England", region: "gb" },
  "the-cherry-orchard": { label: "Russia", region: "ru" },
  "bel-ami": { label: "Paris", region: "fr" },
  liliom: { label: "Budapest", region: "hu" },
  "african-farm": { label: "South Africa", region: "za" },
  underdogs: { label: "Mexico", region: "mx" },
  "miss-julie": { label: "Sweden", region: "se" },
  "sister-carrie": { label: "Chicago", region: "us" },
  "my-antonia": { label: "Nebraska", region: "us" },
  "o-pioneers": { label: "Nebraska", region: "us" },
  "ethan-frome": { label: "New England", region: "us" },
  "winesburg-ohio": { label: "Ohio", region: "us" },
  "home-harlem": { label: "Harlem", region: "us" },
  "plum-bun": { label: "Philadelphia", region: "us" },
  kim: { label: "Lahore — Wonder House", region: "in" },
  "plain-tales-from-the-hills": { label: "India", region: "in" },
  ulysses: { label: "Dublin", region: "ie" },
  dubliners: { label: "Dublin", region: "ie" },
  "a-portrait-of-the-artist-as-a-young-man": { label: "Dublin", region: "ie" },
  venice: { label: "Venice", region: "it" },
  malavoglia: { label: "Sicily", region: "it" },
  cat: { label: "Tokyo", region: "jp" },
  kokoro: { label: "Tokyo", region: "jp" },
  genji: { label: "Japan", region: "jp" },
  swann: { label: "France", region: "fr" },
  nana: { label: "Paris", region: "fr" },
  "after-the-divorce": { label: "Sardinia", region: "it" },

  // Adapted by tbr — remakes, not locked-recommend / Next classics
  // Mike hard rule: ≤1/3 America-set (exactly 3/14 US keepers).
  "miss-brill-adapted": { label: "Menton / French Riviera", region: "fr" },
  "prefer-not": { label: "New York", region: "us" },
  "late-season": { label: "Yalta / Moscow", region: "ru" },
  "between-the-drop-and-the-water": {
    label: "Hudson River, New York",
    region: "us",
  },
  "he-woke-changed": { label: "Prague", region: "cz" },
  "the-pattern": { label: "Hudson, New York", region: "us" },
  "a-coat-worthy-of-respect": { label: "St. Petersburg", region: "ru" },
  "what-she-borrowed": { label: "Paris", region: "fr" },
  "it-was-not-nervousness": { label: "East London", region: "gb" },
  "during-carnival": { label: "Venice", region: "it" },
  "what-we-sold": { label: "London", region: "gb" },
  "bliss-tokyo": { label: "Tokyo", region: "jp" },
  "open-window-singapore": { label: "Singapore", region: "sg" },
  "story-of-an-hour-buenos-aires": { label: "Buenos Aires", region: "ar" },
  "masque-rio": { label: "Rio de Janeiro", region: "br" },
  "boule-de-suif-istanbul": { label: "Istanbul", region: "tr" },
  "happy-prince-hong-kong": { label: "Hong Kong", region: "hk" },
  "hunger-artist-milan": { label: "Milan", region: "it" },
  "the-nose-cape-town": { label: "Cape Town", region: "za" },
  "queen-of-spades-paris": { label: "Paris", region: "fr" },
  "decapitated-chicken-lisbon": { label: "Lisbon", region: "pt" },
  "madame-bovary-tokyo": { label: "Tokyo", region: "jp" },
  "dorian-gray-shanghai": { label: "Shanghai", region: "cn" },
  "anna-karenina-milan": { label: "Milan", region: "it" },
  "jane-eyre-singapore": { label: "Singapore", region: "sg" },
  "pride-prejudice-buenos-aires": { label: "Buenos Aires", region: "ar" },
  "dracula-istanbul": { label: "Istanbul", region: "tr" },
  "crime-punishment-cape-town": { label: "Cape Town", region: "za" },
  "age-of-innocence-venice": { label: "Venice", region: "it" },
  "tess-lisbon": { label: "Lisbon", region: "pt" },
  "scarlet-letter-kyoto": { label: "Kyoto", region: "jp" },
  "wuthering-heights-rio": { label: "Rio de Janeiro", region: "br" },
  "garden-party-barcelona": { label: "Barcelona", region: "es" },
  "usher-prague": { label: "Prague", region: "cz" },
  "araby-seville": { label: "Seville", region: "es" },
};

/** Country-of-origin → reader label + silhouette when no setting override. */
const COUNTRY_PLACE: Record<string, WorkPlace> = {
  "United States": { label: "United States", region: "us" },
  "United Kingdom": { label: "England", region: "gb" },
  Ireland: { label: "Ireland", region: "ie" },
  Scotland: { label: "Scotland", region: "gb" },
  Wales: { label: "Wales", region: "gb" },
  England: { label: "England", region: "gb" },
  France: { label: "France", region: "fr" },
  Germany: { label: "Germany", region: "de" },
  Austria: { label: "Austria", region: "at" },
  Russia: { label: "Russia", region: "ru" },
  Japan: { label: "Japan", region: "jp" },
  China: { label: "China", region: "cn" },
  Italy: { label: "Italy", region: "it" },
  Spain: { label: "Spain", region: "es" },
  Portugal: { label: "Portugal", region: "pt" },
  Brazil: { label: "Brazil", region: "br" },
  Mexico: { label: "Mexico", region: "mx" },
  Argentina: { label: "Argentina", region: "ar" },
  India: { label: "India", region: "in" },
  Iran: { label: "Persia", region: "ir" },
  "South Africa": { label: "South Africa", region: "za" },
  Australia: { label: "Australia", region: "au" },
  "New Zealand": { label: "New Zealand", region: "nz" },
  Canada: { label: "Canada", region: "ca" },
  Jamaica: { label: "Jamaica", region: "jm" },
  Hungary: { label: "Hungary", region: "hu" },
  Czechia: { label: "Czechia", region: "cz" },
  Poland: { label: "Poland", region: "pl" },
  Netherlands: { label: "Netherlands", region: "nl" },
  Belgium: { label: "Belgium", region: "be" },
  Sweden: { label: "Sweden", region: "se" },
  Norway: { label: "Norway", region: "no" },
  Denmark: { label: "Denmark", region: "dk" },
  Finland: { label: "Finland", region: "fi" },
  Greece: { label: "Greece", region: "gr" },
  Turkey: { label: "Turkey", region: "tr" },
  Ukraine: { label: "Ukraine", region: "ua" },
  Romania: { label: "Romania", region: "ro" },
  Korea: { label: "Korea", region: "kr" },
  Egypt: { label: "Egypt", region: "eg" },
  Lebanon: { label: "Lebanon", region: "lb" },
  Peru: { label: "Peru", region: "pe" },
  Philippines: { label: "Philippines", region: "ph" },
  Colombia: { label: "Colombia", region: "co" },
  Cuba: { label: "Cuba", region: "cu" },
  Iceland: { label: "Iceland", region: "is" },
  Uruguay: { label: "Uruguay", region: "uy" },
  Venezuela: { label: "Venezuela", region: "ve" },
  Guyana: { label: "Guyana", region: "gy" },
  Guatemala: { label: "Guatemala", region: "gt" },
  Nicaragua: { label: "Nicaragua", region: "ni" },
  Malaysia: { label: "Malaysia", region: "my" },
  Vietnam: { label: "Vietnam", region: "vn" },
  Laos: { label: "Laos", region: "la" },
  Thailand: { label: "Thailand", region: "th" },
  Indonesia: { label: "Indonesia", region: "id" },
  Iraq: { label: "Iraq", region: "iq" },
  Belarus: { label: "Belarus", region: "by" },
  Palestine: { label: "Palestine", region: "ps" },
  Israel: { label: "Israel", region: "il" },
  Ghana: { label: "Ghana", region: "gh" },
};

function withShape(place: WorkPlace | undefined): WorkPlace | null {
  if (!place) return null;
  if (!REGION_SHAPES[place.region]) return null;
  return place;
}

export function placeFor(work: PlaceRef): WorkPlace | null {
  const curated = withShape(WORK_PLACE[work.id]);
  if (curated) return curated;
  const country = countryFor(work);
  if (!country) return null;
  return withShape(COUNTRY_PLACE[country]);
}

export function placeForId(id: string): WorkPlace | null {
  const work = shelfWork(id);
  if (work) return placeFor(work);
  return withShape(WORK_PLACE[id]);
}

export function hasPlaceShape(region: string): region is PlaceRegion {
  return region in REGION_SHAPES;
}

/** Locked recommend + Next track + Adapted + ritual-lane ids (unique, catalog order). */
export function surfacedPlaceWorkIds(): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const id of [
    ...FEATURED_CAROUSEL_IDS,
    ...NEXT_FEATURED_TRACK_IDS,
    ...ADAPTED_BY_SALON_IDS,
  ]) {
    if (seen.has(id)) continue;
    seen.add(id);
    out.push(id);
  }
  for (const lane of RITUAL_LANES) {
    for (const id of lane.workIds) {
      if (seen.has(id)) continue;
      seen.add(id);
      out.push(id);
    }
  }
  return out;
}
