/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as CuratorRouteImport } from './routes/curator'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FormRouteImport } from './routes/form'
import { Route as GlassRouteImport } from './routes/glass'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as PageRouteImport } from './routes/page'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RitualsRouteImport } from './routes/rituals'
import { Route as ShuffleRouteImport } from './routes/shuffle'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as TogetherRouteImport } from './routes/together'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ClubClubIdRouteImport } from './routes/club.$clubId'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileCollectionRouteImport } from './routes/profile.collection'
import { Route as ReadWorkIdRouteImport } from './routes/read.$workId'
import { Route as ReaderReaderIdRouteImport } from './routes/reader.$readerId'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ClubInviteTokenRouteImport } from './routes/club.invite.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratorRoute = CuratorRouteImport.update({
  id: '/curator',
  path: '/curator',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassRoute = GlassRouteImport.update({
  id: '/glass',
  path: '/glass',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualsRoute = RitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuffleRoute = ShuffleRouteImport.update({
  id: '/shuffle',
  path: '/shuffle',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const TogetherRoute = TogetherRouteImport.update({
  id: '/together',
  path: '/together',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubClubIdRoute = ClubClubIdRouteImport.update({
  id: '/club/$clubId',
  path: '/club/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileCollectionRoute = ProfileCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => ProfileRoute,
} as any)
const ReadWorkIdRoute = ReadWorkIdRouteImport.update({
  id: '/read/$workId',
  path: '/read/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderReaderIdRoute = ReaderReaderIdRouteImport.update({
  id: '/reader/$readerId',
  path: '/reader/$readerId',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubInviteTokenRoute = ClubInviteTokenRouteImport.update({
  id: '/club/invite/$token',
  path: '/club/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/curator': typeof CuratorRoute
  '/desk': typeof DeskRoute
  '/form': typeof FormRoute
  '/glass': typeof GlassRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/page': typeof PageRoute
  '/profile': typeof ProfileRouteWithChildren
  '/rituals': typeof RitualsRoute
  '/shuffle': typeof ShuffleRoute
  '/stores': typeof StoresRoute
  '/together': typeof TogetherRoute
  '/api/rtc': typeof ApiRtcRoute
  '/club/$clubId': typeof ClubClubIdRoute
  '/profile/collection': typeof ProfileCollectionRoute
  '/read/$workId': typeof ReadWorkIdRoute
  '/reader/$readerId': typeof ReaderReaderIdRoute
  '/s/$token': typeof STokenRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/club/invite/$token': typeof ClubInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/curator': typeof CuratorRoute
  '/desk': typeof DeskRoute
  '/form': typeof FormRoute
  '/glass': typeof GlassRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/page': typeof PageRoute
  '/rituals': typeof RitualsRoute
  '/shuffle': typeof ShuffleRoute
  '/stores': typeof StoresRoute
  '/together': typeof TogetherRoute
  '/api/rtc': typeof ApiRtcRoute
  '/club/$clubId': typeof ClubClubIdRoute
  '/profile/collection': typeof ProfileCollectionRoute
  '/read/$workId': typeof ReadWorkIdRoute
  '/reader/$readerId': typeof ReaderReaderIdRoute
  '/s/$token': typeof STokenRoute
  '/profile': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/club/invite/$token': typeof ClubInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/curator': typeof CuratorRoute
  '/desk': typeof DeskRoute
  '/form': typeof FormRoute
  '/glass': typeof GlassRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/page': typeof PageRoute
  '/profile': typeof ProfileRouteWithChildren
  '/rituals': typeof RitualsRoute
  '/shuffle': typeof ShuffleRoute
  '/stores': typeof StoresRoute
  '/together': typeof TogetherRoute
  '/api/rtc': typeof ApiRtcRoute
  '/club/$clubId': typeof ClubClubIdRoute
  '/profile/collection': typeof ProfileCollectionRoute
  '/read/$workId': typeof ReadWorkIdRoute
  '/reader/$readerId': typeof ReaderReaderIdRoute
  '/s/$token': typeof STokenRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/club/invite/$token': typeof ClubInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clubs'
    | '/curator'
    | '/desk'
    | '/form'
    | '/glass'
    | '/login'
    | '/map'
    | '/page'
    | '/profile'
    | '/rituals'
    | '/shuffle'
    | '/stores'
    | '/together'
    | '/api/rtc'
    | '/club/$clubId'
    | '/profile/collection'
    | '/read/$workId'
    | '/reader/$readerId'
    | '/s/$token'
    | '/profile/'
    | '/api/auth/$'
    | '/club/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clubs'
    | '/curator'
    | '/desk'
    | '/form'
    | '/glass'
    | '/login'
    | '/map'
    | '/page'
    | '/rituals'
    | '/shuffle'
    | '/stores'
    | '/together'
    | '/api/rtc'
    | '/club/$clubId'
    | '/profile/collection'
    | '/read/$workId'
    | '/reader/$readerId'
    | '/s/$token'
    | '/profile'
    | '/api/auth/$'
    | '/club/invite/$token'
  id:
    | '__root__'
    | '/'
    | '/clubs'
    | '/curator'
    | '/desk'
    | '/form'
    | '/glass'
    | '/login'
    | '/map'
    | '/page'
    | '/profile'
    | '/rituals'
    | '/shuffle'
    | '/stores'
    | '/together'
    | '/api/rtc'
    | '/club/$clubId'
    | '/profile/collection'
    | '/read/$workId'
    | '/reader/$readerId'
    | '/s/$token'
    | '/profile/'
    | '/api/auth/$'
    | '/club/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubsRoute: typeof ClubsRoute
  CuratorRoute: typeof CuratorRoute
  DeskRoute: typeof DeskRoute
  FormRoute: typeof FormRoute
  GlassRoute: typeof GlassRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PageRoute: typeof PageRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RitualsRoute: typeof RitualsRoute
  ShuffleRoute: typeof ShuffleRoute
  StoresRoute: typeof StoresRoute
  TogetherRoute: typeof TogetherRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ClubClubIdRoute: typeof ClubClubIdRoute
  ReadWorkIdRoute: typeof ReadWorkIdRoute
  ReaderReaderIdRoute: typeof ReaderReaderIdRoute
  STokenRoute: typeof STokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ClubInviteTokenRoute: typeof ClubInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curator': {
      id: '/curator'
      path: '/curator'
      fullPath: '/curator'
      preLoaderRoute: typeof CuratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glass': {
      id: '/glass'
      path: '/glass'
      fullPath: '/glass'
      preLoaderRoute: typeof GlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page': {
      id: '/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rituals': {
      id: '/rituals'
      path: '/rituals'
      fullPath: '/rituals'
      preLoaderRoute: typeof RitualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuffle': {
      id: '/shuffle'
      path: '/shuffle'
      fullPath: '/shuffle'
      preLoaderRoute: typeof ShuffleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/together': {
      id: '/together'
      path: '/together'
      fullPath: '/together'
      preLoaderRoute: typeof TogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$clubId': {
      id: '/club/$clubId'
      path: '/club/$clubId'
      fullPath: '/club/$clubId'
      preLoaderRoute: typeof ClubClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/collection': {
      id: '/profile/collection'
      path: '/collection'
      fullPath: '/profile/collection'
      preLoaderRoute: typeof ProfileCollectionRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/read/$workId': {
      id: '/read/$workId'
      path: '/read/$workId'
      fullPath: '/read/$workId'
      preLoaderRoute: typeof ReadWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$readerId': {
      id: '/reader/$readerId'
      path: '/reader/$readerId'
      fullPath: '/reader/$readerId'
      preLoaderRoute: typeof ReaderReaderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/invite/$token': {
      id: '/club/invite/$token'
      path: '/club/invite/$token'
      fullPath: '/club/invite/$token'
      preLoaderRoute: typeof ClubInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileCollectionRoute: typeof ProfileCollectionRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileCollectionRoute: ProfileCollectionRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubsRoute: ClubsRoute,
  CuratorRoute: CuratorRoute,
  DeskRoute: DeskRoute,
  FormRoute: FormRoute,
  GlassRoute: GlassRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PageRoute: PageRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RitualsRoute: RitualsRoute,
  ShuffleRoute: ShuffleRoute,
  StoresRoute: StoresRoute,
  TogetherRoute: TogetherRoute,
  ApiRtcRoute: ApiRtcRoute,
  ClubClubIdRoute: ClubClubIdRoute,
  ReadWorkIdRoute: ReadWorkIdRoute,
  ReaderReaderIdRoute: ReaderReaderIdRoute,
  STokenRoute: STokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ClubInviteTokenRoute: ClubInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
